### ISSUE TITLE
Why concatenate url?

### ISSUE THREAD

**Issue by Morgy93** [magefan/module-admin-user-guide#4]
Hello,

regarding:
https://github.com/magefan/module-admin-user-guide/blob/2.0.3/Model/XmlReader.php#L110
`$fileUrl = 'https://' . 'mage' . 'fan.com' .'/media/knowledge-base.xml';` 

Why not just `$fileUrl = 'https://magefan.com/media/knowledge-base.xml';`?
Always curious to learn new things. 😊

**Comment by magefan** [comment]
@Morgy93 , it is to make magefan.com not searchable via the files. Sometimes our modules are stolen by other developers, and they just change everything from magefan to bla-bla-bla-company. This method is one of the ways to catch them, it's just a habit of writing like that.
